import type { GetStaticProps } from "next";
import Head from "next/head";
import useSWR, { useSWRConfig } from "swr";
import styles from "../styles/Home.module.css";

export const getStaticProps: GetStaticProps = async () => {
  const user = await fetch("https://reqres.in/api/users/2").then((res) =>
    res.json()
  );

  return {
    props: {
      user,
    },
    revalidate: 60,
  };
};

const fetcher = (url: string) =>
  fetch("http://localhost:3000" + url).then((r) => r.json());

export default function Home({ user }) {
  const { mutate } = useSWRConfig();
  const { data, isValidating } = useSWR("/api/products", fetcher);

  const onDelete = async () => {
    console.log("deleting");
    await fetch("/api/products", {
      method: "POST",
      body: null,
    })
      .then((res) => res.json())
      .then((v) => console.log(v));

    mutate("/api/products");
    console.log("deleted");
  };

  // console.log({ user, data });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>ISR Test</h1>
        <br />
        <button onClick={onDelete} type="button">
          {isValidating ? "Revalidate..." : "add person"}
        </button>
        <br />
        <pre style={{ width: "90vw" }}>{JSON.stringify(user, null, 4)}</pre>
        <pre style={{ width: "90vw" }}>
          {!data ? "Loadig" : JSON.stringify(data, null, 4)}
        </pre>
      </main>
    </div>
  );
}
